services:
  backend:
    volumes:
      - /app
      - ./backend:/app
    container_name: integer-to-roman-backend
    restart: unless-stopped
    build:
      context: backend
      dockerfile: ./Dockerfile.dev
    working_dir: /app
    ports:
      - 8081:8081
  frontend:
    container_name: integer-to-roman-frontend
    build:
      context: frontend
      dockerfile: ./Dockerfile.dev
    working_dir: /app
    ports:
      - 8080:8080

