services:
  prometheus:
    image: prom/prometheus
    container_name: integer-to-roman-prometheus-dev
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus:/prometheus
    ports:
      - 9090:9090
    expose:
      - 9090
    networks:
      - monitoring
    # command:
    #   - "--config.file=/etc/prometheus/prometheus.yml" 
  grafana:
    image: grafana/grafana
    container_name: integer-to-roman-grafana-dev
    ports:
      - 3000:3000 
    depends_on:
      - prometheus
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - monitoring
  backend:
    volumes:
      - /app
      - ./backend:/app
      - backend-ignore:/app/node_modules
    image: integer-to-roman-backend-dev
    container_name: integer-to-roman-backend-dev
    restart: unless-stopped
    build:
      context: backend
      dockerfile: ./Dockerfile.dev
    working_dir: /app
    ports:
      - 8080:8080
    networks:
      - monitoring 
  frontend:
    volumes:
      - ./frontend:/app
      - /app/node_modules
    image: integer-to-roman-frontend-dev
    container_name: integer-to-roman-frontend-dev
    build:
      context: frontend
      dockerfile: ./Dockerfile.dev
    working_dir: /app
    ports:
      - 4000:4000
    environment:
      - VITE_API_URI=http://localhost:8080
    depends_on:
      - backend
    networks:
      - monitoring 
volumes:
  backend-ignore:
  prometheus:
  grafana:
networks:
  public:
  private:
  monitoring:
    driver: bridge
