name: Integer to Roman Numeral CI 

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    # strategy:
    #   matrix:
    #     include:
    #       - image: integer-to-roman-numeral/frontend
    #         dockerfile: ./frontend/Dockerfile
    #       - image: integer-to-roman-numeral/backend
    #         dockerfile: ./backend/Dockerfile

    permissions:
      contents: read
      packages: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }} 
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Test Frontend
        run: cd frontend; npm ci; npm test

      - name: Test Backend 
        run: cd backend; npm ci; npm test

      # - name: Extract metadata (tags, labels) for Docker
      #   id: meta
      #   uses: docker/metadata-action@v4
      #   with:
      #     images: ${{ matrix.image }}
      
      - name: Build backend
        uses: docker/build-push-action@v6
        with:
          context: backend
          platforms: linux/amd64,linux/arm64
          # push: true
          tags: ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}/backend:latest
      
      # - name: Build and push
      #   uses: docker/build-push-action@v6
      #   with:
      #     context: .
      #     file: ${{ matrix.dockerfile }}
      #     platforms: linux/amd64,linux/arm64
      #     push: true
      #     tags: ${{ steps.meta.outputs.tags }}
      #     labels: ${{ steps.meta.outputs.labels }}
