name: Integer to Roman Numeral CI 

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    # strategy:
    #   matrix:
    #     include:
    #       - image: integer-to-roman-numeral/frontend
    #         dockerfile: frontend/Dockerfile
    #       - image: integer-to-roman-numeral/backend
    #         dockerfile: backend/Dockerfile
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }} 
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Test Frontend
        run: cd frontend; npm ci; npm test

      - name: Test Backend 
        run: cd backend; npm ci; npm test
      
      - name: Build and push frontend
        uses: docker/build-push-action@v6
        with:
          context: frontend 
          # file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}/frontend:latest

      - name: Build and push backend
        uses: docker/build-push-action@v6
        with:
          context: backend
          # file: Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}/backend:latest
